# Generated by Django 3.2.6 on 2022-03-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spent', '0003_auto_20220322_1235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-track_id__start_date']},
        ),
        migrations.RenameField(
            model_name='budgetclassitem',
            old_name='budget_catogery',
            new_name='budget_category',
        ),
        migrations.AlterField(
            model_name='budget',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
